apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cron-container
            image: busybox
            args: ["/bin/sh", "-c", "date; echo Hello from the K8s cluster"]
